name: Build project
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: static
          path: dist/
          retention-days: 1

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/download-artifact@v3
        with:
          name: static
          path: dist/

      - name: Build project to docker
        timeout-minutes: 5
        run: docker compose build

      - name: Run project
        run: docker compose up -d

      - name: Build and run tests
        timeout-minutes: 5
        run: |
          cd tests
          npm ci
          node index.mjs --url=http://localhost:8080
        
      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v